services:
  php:
    build:
      context: build
    volumes:
      - ./:/var/www/html
  database:
    #user: "${UID}:${GID}"
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MARIADB_DATABASE: ${MYSQL_DATABASE:-database}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: