services:
    server:
        image: nginx:alpine
        ports:
            - "${SERVER_PORT:-8080}:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        environment:
            MYSQL_HOST: ${DB_HOST:-database}
            MYSQL_DATABASE: ${DB_DATABASE:-database}
            MYSQL_USER: ${DB_USER_NAME:-user}
            MYSQL_PASSWORD: ${DB_USER_PASSWORD:-password}

    php:
        build: ./docker/php
        volumes:
            - ./:/var/www/html
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            MYSQL_HOST: ${DB_HOST:-database}
            MYSQL_DATABASE: ${DB_DATABASE:-database}
            MYSQL_USER: ${DB_USER_NAME:-user}
            MYSQL_PASSWORD: ${DB_USER_PASSWORD:-password}
            
    database:
        image: mysql
        # image: mariadb:11 # it's up to you to choose mysql or mariadb
        # user: "${UID}:${GID}" # uncomment this line if you want to set the user to match host user
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD:-password}
            MYSQL_DATABASE: ${DB_DATABASE:-database}
            MYSQL_USER: ${DB_USER_NAME:-user}
            MYSQL_PASSWORD: ${DB_USER_PASSWORD:-password}
        volumes:
            - ./docker/db_data:/var/lib/mysql
        ports:
            - "${DB_PORT:-3306}:3306"

volumes:
    db-data:
