version: '3.8'
services:
  php: 
    build: ./docker/php
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - ${PHP_PORT:-8080}:80
    volumes:
      - ./:/var/www/html
    command: php -S 0.0.0.0:80 -t public